apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb
  namespace: default
  labels:
    app: windows-smb
spec:
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: 1Gi
  storageClassName: smb-class