apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-smb-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: windows-smb
  template:
    metadata:
      labels:
        app: windows-smb
    spec:
      containers:
        - name: windows-smb
          image: registry.kubernetes.com/windows-nfs:1.0.0
          volumeMounts:
            - name: application-smb-storage
              mountPath: "/ssm/nfs"
              subPath: Data
      volumes:
        - name: application-smb-storage
          persistentVolumeClaim:
            claimName: pvc-smb
      nodeSelector:
        "kubernetes.io/os": windows
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"