apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/healthy"
spec:
  selector:
     app: nginx
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80