apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-smb-server
  namespace: default
  labels:
    app: smb-server-nfs
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client-smb-server