apiVersion: v1
kind: Secret
metadata:
  name: {{ template "smb-server.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "smb-server.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.smb.username | default "smb" | b64enc | quote }}
  password: {{ .Values.smb.password | default "1234" | b64enc | quote }}
