driver:
  name: smb.csi.k8s.io
  
controller:
  name: csi-smb-controller
  
serviceAccount:
  controller: csi-smb-controller-sa
  node: csi-smb-node-sa

linux:
  enabled: false

windows:
  enabled: true
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"