replicaCount: 1


smb:
  nfsEnable: false
  username: ""
  password: ""

  accessMode: 'ReadWriteOnce'
  size: 10Gi
  storageClass: '-'
  


service:
  type: LoadBalancer
  # clusterIP:
  # loadBalancerIP:
  # loadBalancerSourceRanges:
  port: 445