apiVersion: v1
entries:
  csi-driver-smb:
  - apiVersion: v1
    appVersion: latest
    created: "2023-05-28T02:39:22.185832547Z"
    description: SMB CSI Driver for Kubernetes
    digest: 3c3d4d66bf84296fdc48025406c40762bffd348ff414ebde6ae85a69d57cfe4b
    name: csi-driver-smb
    urls:
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts/latest/csi-driver-smb-v0.0.0.tgz
    version: v0.0.0