apiVersion: v1
kind: Pod
metadata:
  name: network-test-pod
spec:
  containers:
    - name: network-test-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - apk update && apk add curl && sleep 3600