replicaCount: 1


smb:
  nfsEnable: true
  username: "windowssmb"
  password: "qwer1234!@"

  accessMode: 'ReadWriteOnce'
  size: 10Gi
  storageClass: "nfs-client-smb-server"

service:
  type: LoadBalancer
  # clusterIP:
  # loadBalancerIP:
  # loadBalancerSourceRanges:
  port: 445