kind: Deployment
apiVersion: apps/v1
metadata:
  name: smb-server-nfs-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smb-server-nfs
  template:
    metadata:
      name: smb-server-nfs
      labels:
        app: smb-server-nfs
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: smb-server-nfs
          image: andyzhangx/samba:win-fix
          env:
            - name: PERMISSIONS
              value: "0777"
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: smb-server-credentials
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smb-server-credentials
                  key: password
          args: ["-u", "$(USERNAME);$(PASSWORD)", "-s", "share;/smbshare/;yes;no;no;all;none", "-p"]
          volumeMounts:
            - mountPath: /smbshare
              name: data-volume
          ports:
            - containerPort: 445
      #volumes:
      #  - name: data-volume
      #    hostPath:
      #      path: /home/kubernetes/smbshare-volume  # modify this to specify another path to store smb share data
      #      type: DirectoryOrCreate
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: pvc-smb-server