apiVersion: v1
kind: Pod
metadata:
  name: windows-smb-client-pod
spec:
  containers:
  - image: registry.kubernetes.com/windows-smb:1.1.2
    name: windows-smb
    env:
      - name: DRIVELETTER
        value: "Z:"
      - name: networkPath
        value: "\\\\windows-smb-server.analysis-elasticsearch.svc.cluster.local\\share"
      - name: username
        valueFrom:
          secretKeyRef:
            name: windows-smb-server-credentials
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: windows-smb-server-credentials
            key: password
  nodeSelector:
    kubernetes.io/os: windows
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    - effect: NoExecute	
      key: node.kubernetes.io/not-ready	
      operator: Exists	
      tolerationSeconds: 300	
    - effect: NoExecute	
      key: node.kubernetes.io/unreachable	
      operator: Exists	
      tolerationSeconds: 300